[tool.bumpversion]
current_version = "0.3.3"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = false
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
commit = false
message = "Bump version: {current_version} → {new_version}"
moveable_tags = []
commit_args = ""
setup_hooks = []
pre_commit_hooks = []
post_commit_hooks = []

[[tool.bumpversion.files]]
filename = "talks_reducer/__about__.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'

[[tool.bumpversion.files]]
filename = "version.txt"
search = "    filevers=({major}, {minor}, {patch}, 0),"
replace = "    filevers=({major}, {minor}, {patch}, 0),"

[[tool.bumpversion.files]]
filename = "version.txt"
search = "    prodvers=({major}, {minor}, {patch}, 0),"
replace = "    prodvers=({major}, {minor}, {patch}, 0),"

[[tool.bumpversion.files]]
filename = "version.txt"
search = "        StringStruct(u'FileVersion', u'{major}.{minor}.{patch}.0')"
replace = "        StringStruct(u'FileVersion', u'{major}.{minor}.{patch}.0')"

[[tool.bumpversion.files]]
filename = "version.txt"
search = "        StringStruct(u'ProductVersion', u'{major}.{minor}.{patch}.0')"
replace = "        StringStruct(u'ProductVersion', u'{major}.{minor}.{patch}.0')"
